name: Theme Check

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  theme-check:
    runs-on: ubuntu-latest
    name: Theme Check
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Temporarily hide docs folder
        run: |
          if [ -d "docs" ]; then
            mv docs ../docs-temp
          fi

      - name: Run Theme Review Tests
        id: theme-test
        uses: WordPress/theme-review-action@trunk
        with:
          accessible-ready: true
          ui-debug: true

      - name: Restore docs folder
        if: always()
        run: |
          if [ -d "../docs-temp" ]; then
            mv ../docs-temp docs
          fi
